## AQI of India on 29112025
#### Data Cleaning on this dataset
<p>Downloaded this dataset from Indian government website to do some data cleaning and visualizations.</p>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/kaggle/input/aqi-of-india-on-29112025/AQI of India on 29112025.csv")

In [3]:
df.shape

(3331, 11)

In [4]:
df.columns

Index(['country', 'state', 'city', 'station', 'last_update', 'latitude',
       'longitude', 'pollutant_id', 'pollutant_min', 'pollutant_max',
       'pollutant_avg'],
      dtype='object')

In [5]:
df.dtypes

country           object
state             object
city              object
station           object
last_update       object
latitude         float64
longitude        float64
pollutant_id      object
pollutant_min    float64
pollutant_max    float64
pollutant_avg    float64
dtype: object

In [6]:
df.tail()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
3326,India,West_Bengal,Kolkata,"Rabindra Bharati University, Kolkata - WBPCB",29-11-2025 23:00:00,22.627847,88.380669,PM2.5,50.0,297.0,149.0
3327,India,West_Bengal,Kolkata,"Rabindra Bharati University, Kolkata - WBPCB",29-11-2025 23:00:00,22.627847,88.380669,CO,28.0,118.0,76.0
3328,India,West_Bengal,Kolkata,"Rabindra Sarobar, Kolkata - WBPCB",29-11-2025 23:00:00,22.511060,88.351420,PM2.5,57.0,125.0,86.0
3329,India,West_Bengal,Kolkata,"Victoria, Kolkata - WBPCB",29-11-2025 23:00:00,22.544808,88.340369,CO,16.0,96.0,49.0
3330,India,West_Bengal,Siliguri,"Ward-32 Bapupara, Siliguri - WBPCB",29-11-2025 23:00:00,26.687923,88.415250,PM10,53.0,180.0,84.0

In [7]:
df.last_update.value_counts()

last_update
29-11-2025 23:00:00    3331
Name: count, dtype: int64

In [8]:
df.shape

(3331, 11)

In [9]:
len(df[df['state']=='Bihar'])

231

In [10]:
df.city[df['state']=='Bihar'].value_counts()

city
Patna           40
Gaya            19
Muzaffarpur     19
Bhagalpur       14
Araria           7
Hajipur          7
Sasaram          7
Rajgir           7
Samastipur       7
Siwan            7
Munger           7
Saharsa          7
Purnia           7
Chhapra          7
Arrah            7
Buxar            7
Motihari         7
Manguraha        7
Kishanganj       7
Katihar          7
Bettiah          7
Begusarai        7
Aurangabad       7
Bihar Sharif     6
Name: count, dtype: int64

In [11]:
# fetching details of Patna only
df[['pollutant_id','pollutant_min','pollutant_max',]][df['city']=='Patna']

     pollutant_id  pollutant_min  pollutant_max
58           PM10           64.0           86.0
59            SO2            9.0           13.0
60          OZONE            8.0           11.0
61          PM2.5           48.0          195.0
62          OZONE           22.0           31.0
67           PM10           60.0          114.0
68            SO2            6.0            8.0
69            NH3            5.0           15.0
70          OZONE            7.0           47.0
765         PM2.5           59.0           69.0
766           SO2            1.0           28.0
767         OZONE           25.0           55.0
770           SO2            7.0           10.0
771         PM2.5           37.0           94.0
772         PM2.5           83.0          185.0
1424          SO2            7.0           10.0
1425           CO           32.0           90.0
1426          NO2            1.0           17.0
1427          NO2            6.0           12.0
1428          NH3            4.0            5.0
1429           CO           32.0           88.0
1430        OZONE            4.0           40.0
1431         PM10           95.0          153.0
1438          NO2           36.0           82.0
2097          NO2           17.0           41.0
2098          NH3            4.0            5.0
2099        PM2.5           15.0          160.0
2100           CO           30.0           67.0
2101         PM10           60.0          146.0
2102           CO           36.0          109.0
2105        PM2.5           62.0          188.0
2106          NO2           19.0           22.0
2110         PM10           75.0          162.0
2692           CO           28.0           83.0
2693          NH3            5.0            5.0
2694          SO2            1.0            2.0
2695           CO           42.0          105.0
2696        OZONE           50.0          319.0
2709          NO2            2.0           98.0
2710          NH3            4.0           10.0

In [12]:
df.pollutant_id.unique()

array(['SO2', 'OZONE', 'NO2', 'CO', 'PM10', 'NH3', 'PM2.5'], dtype=object)

In [13]:
df.dtypes

country           object
state             object
city              object
station           object
last_update       object
latitude         float64
longitude        float64
pollutant_id      object
pollutant_min    float64
pollutant_max    float64
pollutant_avg    float64
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3331 entries, 0 to 3330
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        3331 non-null   object
 1   state          3331 non-null   object
 2   city           3331 non-null   object
 3   station        3331 non-null   object
 4   last_update    3331 non-null   object
 5   latitude       3331 non-null   float64
 6   longitude      3331 non-null   float64
 7   pollutant_id   3331 non-null   object
 8   pollutant_min  3093 non-null   float64
 9   pollutant_max  3093 non-null   float64
 10  pollutant_avg  3093 non-null   float64
dtypes: float64(5), object(6)
memory usage: 286.4+ KB

In [15]:
df.isnull().sum()

country            0
state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    238
pollutant_max    238
pollutant_avg    238
dtype: int64

In [16]:
df['pollutant_min'].mean()

30.895570643388297

In [17]:
df.pollutant_min.fillna(df['pollutant_min'].mean(),inplace=True)

/tmp/ipykernel_90/3938094399.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.pollutant_min.fillna(df['pollutant_min'].mean(),inplace=True)

In [18]:
df.pollutant_min.mean()

30.895570643388293

In [19]:
df['pollutant_min'].isnull().sum()

0

In [20]:
df['pollutant_max'].fillna(df.pollutant_max.mean(),inplace=True)

/tmp/ipykernel_90/3065971021.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['pollutant_max'].fillna(df.pollutant_max.mean(),inplace=True)

In [21]:
df['pollutant_max'].isna().sum()

0

In [22]:
df['pollutant_avg'].mean()

57.7950210151956

In [23]:
df['pollutant_avg'] = df['pollutant_avg'].fillna(df['pollutant_avg'].mean())

In [24]:
df['pollutant_avg'].mean()

57.79502101519561

In [25]:
df.isna().sum()

country          0
state            0
city             0
station          0
last_update      0
latitude         0
longitude        0
pollutant_id     0
pollutant_min    0
pollutant_max    0
pollutant_avg    0
dtype: int64

In [26]:
df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Tirupati,"Vaikuntapuram, Tirupati - APPCB",29-11-2025 23:00:00,13.615387,79.409230,SO2,30.895571,93.780472,57.795021
1,India,Andhra_Pradesh,Tirupati,"Vaikuntapuram, Tirupati - APPCB",29-11-2025 23:00:00,13.615387,79.409230,OZONE,16.000000,17.000000,16.000000
2,India,Andhra_Pradesh,Vijayawada,"HB Colony, Vijayawada - APPCB",29-11-2025 23:00:00,16.536107,80.594233,NO2,22.000000,22.000000,22.000000
3,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",29-11-2025 23:00:00,16.509717,80.612222,NO2,43.000000,99.000000,64.000000
4,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",29-11-2025 23:00:00,16.509717,80.612222,CO,36.000000,37.000000,37.000000

In [27]:
df['city']=df['city'].str.title()

In [28]:
df.state = df.state.str.title()

In [29]:
df.isnull().sum()

country          0
state            0
city             0
station          0
last_update      0
latitude         0
longitude        0
pollutant_id     0
pollutant_min    0
pollutant_max    0
pollutant_avg    0
dtype: int64

In [30]:
df.describe()

          latitude    longitude  pollutant_min  pollutant_max  pollutant_avg
count  3331.000000  3331.000000    3331.000000    3331.000000    3331.000000
mean     22.753618    78.645615      30.895571      93.780472      57.795021
std       5.511725     4.853500      33.798357      97.727982      60.849285
min       8.514909    70.909168       1.000000       1.000000       1.000000
25%      19.074813    75.578914       7.000000      20.000000      14.000000
50%      23.549395    77.315741      19.000000      69.000000      40.000000
75%      27.213494    80.594233      40.000000     121.000000      76.000000
max      34.066206    94.636574     319.000000     500.000000     346.000000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3331 entries, 0 to 3330
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        3331 non-null   object
 1   state          3331 non-null   object
 2   city           3331 non-null   object
 3   station        3331 non-null   object
 4   last_update    3331 non-null   object
 5   latitude       3331 non-null   float64
 6   longitude      3331 non-null   float64
 7   pollutant_id   3331 non-null   object
 8   pollutant_min  3331 non-null   float64
 9   pollutant_max  3331 non-null   float64
 10  pollutant_avg  3331 non-null   float64
dtypes: float64(5), object(6)
memory usage: 286.4+ KB

In [32]:
df.last_update

0       29-11-2025 23:00:00
1       29-11-2025 23:00:00
2       29-11-2025 23:00:00
3       29-11-2025 23:00:00
4       29-11-2025 23:00:00
               ...
3326    29-11-2025 23:00:00
3327    29-11-2025 23:00:00
3328    29-11-2025 23:00:00
3329    29-11-2025 23:00:00
3330    29-11-2025 23:00:00
Name: last_update, Length: 3331, dtype: object

In [33]:
df.last_update.dtype

dtype('O')

In [34]:
pd.to_datetime(df['last_update'], dayfirst=True)

0      2025-11-29 23:00:00
1      2025-11-29 23:00:00
2      2025-11-29 23:00:00
3      2025-11-29 23:00:00
4      2025-11-29 23:00:00
               ...
3326   2025-11-29 23:00:00
3327   2025-11-29 23:00:00
3328   2025-11-29 23:00:00
3329   2025-11-29 23:00:00
3330   2025-11-29 23:00:00
Name: last_update, Length: 3331, dtype: datetime64[ns]

In [35]:
df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Tirupati,"Vaikuntapuram, Tirupati - APPCB",29-11-2025 23:00:00,13.615387,79.409230,SO2,30.895571,93.780472,57.795021
1,India,Andhra_Pradesh,Tirupati,"Vaikuntapuram, Tirupati - APPCB",29-11-2025 23:00:00,13.615387,79.409230,OZONE,16.000000,17.000000,16.000000
2,India,Andhra_Pradesh,Vijayawada,"HB Colony, Vijayawada - APPCB",29-11-2025 23:00:00,16.536107,80.594233,NO2,22.000000,22.000000,22.000000
3,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",29-11-2025 23:00:00,16.509717,80.612222,NO2,43.000000,99.000000,64.000000
4,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",29-11-2025 23:00:00,16.509717,80.612222,CO,36.000000,37.000000,37.000000

In [36]:
df['last_update'] = pd.to_datetime(df['last_update'], dayfirst=True)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3331 entries, 0 to 3330
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        3331 non-null   object
 1   state          3331 non-null   object
 2   city           3331 non-null   object
 3   station        3331 non-null   object
 4   last_update    3331 non-null   datetime64[ns]
 5   latitude       3331 non-null   float64
 6   longitude      3331 non-null   float64
 7   pollutant_id   3331 non-null   object
 8   pollutant_min  3331 non-null   float64
 9   pollutant_max  3331 non-null   float64
 10  pollutant_avg  3331 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(5)
memory usage: 286.4+ KB

In [38]:
df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Tirupati,"Vaikuntapuram, Tirupati - APPCB",2025-11-29 23:00:00,13.615387,79.409230,SO2,30.895571,93.780472,57.795021
1,India,Andhra_Pradesh,Tirupati,"Vaikuntapuram, Tirupati - APPCB",2025-11-29 23:00:00,13.615387,79.409230,OZONE,16.000000,17.000000,16.000000
2,India,Andhra_Pradesh,Vijayawada,"HB Colony, Vijayawada - APPCB",2025-11-29 23:00:00,16.536107,80.594233,NO2,22.000000,22.000000,22.000000
3,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",2025-11-29 23:00:00,16.509717,80.612222,NO2,43.000000,99.000000,64.000000
4,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",2025-11-29 23:00:00,16.509717,80.612222,CO,36.000000,37.000000,37.000000

In [39]:
# opened in collab and pushing in github

In [40]:
# succesfully pulled from github after making changes from collab